getgenv().Camlock_Settings = {
    Prediction = 0.159,
    AimPart = "HumanoidRootPart",
    Key = "q",
    AutoPrediction = false,
    Notification = true,
    Button = true, --Only for people who play on mobile
    AntiGroundShots = false,
    UnderGroundResolver = false,

    -- DO NOT TOUCH THIS OR IT WILL NOT WORK --
    Credits = "space_0999",
    DiscordServer = "discord.gg/SKhamGzTdn"
}
 
loadstring(game:HttpGet('https://raw.githubusercontent.com/elxocasXD/Trip-Hub/main/Scripts/Cam%20Lock.lua'))()
